=== AcutronicRobotics/HRIM/models/schemas/module.xsd
<?xml version="1.0"?>
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  elementFormDefault="qualified">

  <xsd:element name="module">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="mandatory" type="mandatoryType" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="optional" type="optionalType" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="type" type="moduleTypeType" use="required"/>
      <xsd:attribute name="description" type="xsd:string" use="optional"/>
      <xsd:attribute name="noNamespaceSchemaLocation" type="xsd:string" use="required"/>
   </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="mandatoryType">
    <xsd:sequence>
      <xsd:element name="topic" type="topicType" minOccurs="8" maxOccurs="unbounded"/>
      <xsd:element name="param" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="optionalType">
    <xsd:sequence>
      <xsd:element name="topic" type="topicType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="param" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>

  <xsd:complexType name="topicType">
    <xsd:sequence>
      <xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element name="response" type="responseType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="topicTypeType" use="required"/>
    <xsd:attribute name="description" type="xsd:string" use="optional"/>
    <xsd:attribute name="fileName" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="propertyType">
    <xsd:choice>
      <xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element name="value" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:choice>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
    <xsd:attribute name="unit" type="xsd:string" use="optional"/>
    <xsd:attribute name="enum" type="xsd:string" use="optional"/>
    <xsd:attribute name="description" type="xsd:string" use="optional"/>
    <xsd:attribute name="fileName" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="responseType">
    <xsd:choice>
      <xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:choice>
  </xsd:complexType>

  <xsd:simpleType name="moduleTypeType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="actuator"/>
      <xsd:enumeration value="cognition"/>
      <xsd:enumeration value="communication"/>
      <xsd:enumeration value="composite"/>
      <xsd:enumeration value="power"/>
      <xsd:enumeration value="sensor"/>
      <xsd:enumeration value="ui"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="topicTypeType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="publish"/>
      <xsd:enumeration value="subscribe"/>
      <xsd:enumeration value="service"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== AcutronicRobotics/HRIM/models/sensor/camera/camera.xml
<?xml version="1.0"?>
<module name="camera" type="sensor" description="defines the messages to interact with a camera"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  noNamespaceSchemaLocation="../../schemas/module.xsd">

  <mandatory>

    <xi:include href="../../generic/base.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/specs.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/image.xml" xpointer="xpointer(//root/topic)"/>

    <param name="frame_id" type="string" description="Sets the TF frame from which the camera is publishing.">
      <value></value>
    </param>

    <param name="width" type="int" unit="px" description="  Resolution: width (width x height)">
      <value></value>
    </param>

    <param name="height" type="int" unit="px" description="Resolution: height (width x height)">
      <value></value>
    </param>

    <param name="frame_rate" type="int" unit="fps" description="Refresh rate.">
      <value></value>
    </param>

    <param name="image_format" type="string" description="Possible values are: 'rgb8', 'rgba8', 'rgb16', 'rgba16', 'bgr8', 'bgra8', 'bgr16', 'bgra16', 'mono8', 'mono16', 'bayerrggb8', 'bayerbggr8', 'bayergbrg8', 'bayergrbg8', 'bayerrggb16', 'bayerbggr16', 'bayergbrg16', 'bayergrbg16'.">
      <value></value>
    </param>

  </mandatory>

  <optional>

    <xi:include href="topics/compressed.xml" xpointer="xpointer(//root/topic)"/>

    <topic name="image_mono" type="publish" description="monochrome, distorted" fileName="Image">
      <xi:include href="topics/image.xml" xpointer="xpointer(//root/topic/property)"/>
    </topic>

    <topic name="image_color" type="publish" description="color, distorted" fileName="Image">
      <xi:include href="topics/image.xml" xpointer="xpointer(//root/topic/property)"/>
    </topic>

    <topic name="image_rect" type="publish" description="monochrome, rectified" fileName="Image">
      <xi:include href="topics/image.xml" xpointer="xpointer(//root/topic/property)"/>
    </topic>

    <topic name="image_rect_color" type="publish" description="color, rectified" fileName="Image">
      <xi:include href="topics/image.xml" xpointer="xpointer(//root/topic/property)"/>
    </topic>

    <xi:include href="topics/cameraInfo.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/setCameraInfo.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/ptz.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/audio.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/reconfiguration.xml" xpointer="xpointer(//root/topic)"/>
    
    <param name="auto_brightness" type="bool" unit="[0/1]" description="Brightness control state">
      <value></value>
    </param>

    <param name="brightness" type="float" unit="%" description="Black level offset">
      <value></value>
    </param>

    <param name="auto_binning" type="bool" unit="[0/1]" description="Combines rectangular neighborhoods of pixels into larger 'super-pixels'">
      <value></value>
    </param>

    <param name="binning_x" type="float" unit="%" description="Binning width">
      <value></value>
    </param>

    <param name="binning_y" type="float" unit="%" description="Binning height">
      <value></value>
    </param>

    <param name="auto_contrast" type="bool" unit="[0/1]" description="Black level offset">
      <value></value>
    </param>

    <param name="contrast" type="float" unit="%" description="Difference in brightness between light and dark areas">
      <value></value>
    </param>

    <param name="auto_exposure" type="bool" unit="[0/1]" description="Combined Iris, Gain and Shutterspeed">
      <value></value>
    </param>

    <param name="exposure" type="float" unit="%" description="Exposure time">
      <value></value>
    </param>

    <param name="auto_focus" type="bool" unit="[0/1]" description="Focus control state">
      <value></value>
    </param>

    <param name="focus" type="float" unit="%" description="Definition of the image">
      <value></value>
    </param>

    <param name="auto_gain" type="bool" unit="[0/1]" description="Gain control state">
      <value></value>
    </param>

    <param name="gain" type="float" unit="%" description="Relative circuit gain">
      <value></value>
    </param>

    <param name="gain_red" type="float" unit="%" description="Gain percentage for red channel">
      <value></value>
    </param>

    <param name="gain_green" type="float" unit="%" description="Gain percentage for green channel">
      <value></value>
    </param>

    <param name="gain_blue" type="float" unit="%" description="Gain percentage for blue channel">
      <value></value>
    </param>

    <param name="auto_gamma" type="bool" unit="[0/1]" description="Gamma expansion exponent">
      <value></value>
    </param>

    <param name="gamma" type="float" unit="%" description="Gamma expansion exponent">
      <value></value>
    </param>

    <param name="auto_hue" type="bool" unit="[0/1]" description="Hue control state">
      <value></value>
    </param>

    <param name="hue" type="float" unit="%" description="Color phase">
      <value></value>
    </param>

    <param name="auto_iris" type="bool" unit="[0/1]" description="Iris control state">
      <value></value>
    </param>

    <param name="iris" type="float" unit="%" description="Iris control">
      <value></value>
    </param>

    <param name="auto_iso" type="bool" unit="[0/1]" description="ISO control state">
      <value></value>
    </param>

    <param name="iso" type="float" unit="%" description="	ISO speed: How sensitive the film is to light">
      <value></value>
    </param>

    <param name="auto_saturation" type="bool" unit="[0/1]" description="Saturation control state">
      <value></value>
    </param>

    <param name="saturation" type="float" unit="%" description="Color saturation">
      <value></value>
    </param>

    <param name="auto_sharpness" type="bool" unit="[0/1]" description="Sharpness control state">
      <value></value>
    </param>

    <param name="sharpness	" type="float" unit="%" description="Image sharpness">
      <value></value>
    </param>

    <param name="auto_shutter" type="bool" unit="[0/1]" description="Shutter control state">
      <value></value>
    </param>

    <param name="shutter" type="float" unit="%" description="Shutter speed: duration of the exposure">
      <value></value>
    </param>

    <param name="auto_white_balance" type="bool" unit="[0/1]" description="White balance control state">
      <value></value>
    </param>

    <param name="white_balance_blue" type="float" unit="%" description="Blue component of white balance">
      <value></value>
    </param>

    <param name="white_balance_red" type="float" unit="%" description="Blue component of red balance">
      <value></value>
    </param>

    <param name="auto_zoom" type="bool" unit="[0/1]" description="Zoom control state">
      <value></value>
    </param>

    <param name="username" type="string" description="Name for camera accessing. The manufacturer will offer a default username.">
      <value></value>
    </param>

    <param name="password" type="string" description="Password for camera accessing. The manufacturer will offer a default password. ">
      <value></value>
    </param>

    <param name="pan_angle_start" type="double" unit="rad" description="Related to ptz topic: pan range start point. Mandatory if ptz topic is added.">
      <value></value>
    </param>

    <param name="pan_angle_end" type="double" unit="rad" description="Related to ptz topic: pan range end point. Mandatory if ptz topic is added.">
      <value></value>
    </param>

    <param name="pan_speed" type="float" unit="rad/s" description="Related to ptz topic: pan speed. Mandatory if ptz topic is added.">
      <value></value>
    </param>

    <param name="tild_angle_start" type="double" unit="rad" description="Related to ptz topic: tild range start point. Mandatory if ptz topic is added.">
      <value></value>
    </param>

    <param name="tild_angle_end" type="double" unit="rad" description="Related to ptz topic: tild range end point. Mandatory if ptz topic is added.">
      <value></value>
    </param>

    <param name="tild_speed" type="float" unit="rad/s" description="Related to ptz topic: tild speed. Mandatory if ptz topic is added.">
      <value></value>
    </param>

    <param name="frecuency_rate" type="int" unit="Hz/s" description="Related to audio_raw topic: audio sampling frecuency. Mandatory if audio_raw topic is added.">
      <value></value>
    </param>

  </optional>

</module>

=== AcutronicRobotics/HRIM/models/sensor/gasdetector/gasdetector.xml
<?xml version="1.0"?>
<module name="gasdetector" type="sensor" description="defines the messages to interact with a gas sensor"
  noNamespaceSchemaLocation="../../schemas/module.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  <mandatory>

    <xi:include href="../../generic/base.xml" xpointer="xpointer(//root/topic)"/>

    <topic name="specs" type="subscribe" description="device features" fileName="SpecsGasDetector">
      <property name="header" type="header" fileName="Header">
        <property name="time" type="time" fileName="Time">
          <property name="sec" type="int32" unit="second">
            <value></value>
          </property>
          <property name="nanosec" type="uint32" unit="nanosecond">
            <value></value>
          </property>
        </property>
        <property name="frame_id" type="string" description="transform frame with which this data is associated">
          <value></value>
        </property>
      </property>
      <property name="particular_specs" type="gasType[]" description="specs of each gas the sensor detects" fileName="GasType">
        <property name="detect_gas_name" type="string" description="the gases that the sensor can detect">
          <value></value>
        </property>
        <property name="gas_detection_technique" type="uint8" unit="enum" enum='{"HROS_GASSENSOR_CATALYTIC": 0, "HROS_GASSENSOR_ECC": 1, "HROS_GASSENSOR_POINTIR": 2, "HROS_GASSENSOR_OPENPATH": 3, "HROS_GASSENSOR_PID": 4, "HROS_GASSENSOR_SEMICONDUCTOR": 5, "HROS_GASSENSOR_PAPERTAPE": 6, "HROS_GASSENSOR_OTHER": 7}' description="type of the sensor">
          <value></value>
        </property>
        <property name="detection_range" type="uint8" description="maximum value">
          <value></value>
        </property>
      </property>
      <property name="response_time" type="uint32" unit="second" description="time the sensor needs to refresh">
        <value></value>
      </property>
      <property name="display" type="boolean" description="true: the gas detector has this extra | false: it doesn't">
        <value></value>
      </property>
      <property name="alarm" type="boolean" description="true: the gas detector has this extra | false: it doesn't">
        <value></value>
      </property>
      <property name="leds" type="boolean" description="true: the gas detector has this extra | false: it doesn't">
        <value></value>
      </property>
      <property name="wifi" type="boolean" description="true: the gas detector has this extra | false: it doesn't">
        <value></value>
      </property>
      <property name="gps" type="boolean" description="true: the gas detector has this extra | false: it doesn't">
        <value></value>
      </property>
    </topic>

    <topic name="gas_measurements" type="subscribe" description="detected gas value" fileName="GasMeasurements">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="measurements" type="gasMeasurement[]" description="the measurement of each sensor" fileName="GasMeasurement">
        <property name="gas_name" type="string" description="the name of the gas">
          <value></value>
        </property>
        <property name="value" type="uint8" description="the measurement of the gas in ppm, ppb or % depending on the gas type">
          <value></value>
        </property>
        <property name="unit" type="string" description="ppm (parts per million), ppb (parts per billion) or %">
          <value></value>
        </property>
      </property>
    </topic>

    <param name="frame_id" type="string" description="tf frame from which the torque sensor is publishing">
      <value></value>
    </param>

    <param name="response_time" type="double" unit="second" description="refresh time">
      <value></value>
    </param>

  </mandatory>
  <optional>

    <topic name="reconfiguration" type="subscribe" description="dynamic reconfiguration of H-ROS systems" fileName="Reconfiguration">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="orientation" type="quaternion" fileName="Quaternion">
        <xi:include href="../../complex/quaternion.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="orientation_covariance" type="float64[9]">
        <value></value>
      </property>
      <property name="angular_velocity" type="vector3" fileName="Vector3">
        <xi:include href="../../complex/vector3.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="angular_velocity_covariance" type="float64[9]">
        <value></value>
      </property>
      <property name="linear_acceleration" type="vector3" fileName="Vector3">
        <xi:include href="../../complex/vector3.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="linear_acceleration_covariance" type="float64[9]">
        <value></value>
      </property>
    </topic>

  </optional>
</module>

=== AcutronicRobotics/HRIM/models/sensor/rangefinder/rangefinder.xml
<?xml version="1.0"?>
<module name="rangefinder" type="sensor" description="defines the messages to interact with a rangefinder"
  noNamespaceSchemaLocation="../../schemas/module.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  <mandatory>

    <xi:include href="../../generic/base.xml" xpointer="xpointer(//root/topic)"/>

    <topic name="specs" type="subscribe" description="device features" fileName="SpecsRangefinder">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="radiation_type" type="uint8" unit="enum" enum='{"ULTRASOUND": 0, "INFRARED": 1}'>
        <value></value>
      </property>
      <property name="field_of_view" type="float32">
        <value></value>
      </property>
      <property name="min_time_measuremets" type="float32">
        <value></value>
      </property>
      <property name="min_operating_temp" type="float32">
        <value></value>
      </property>
      <property name="max_range" type="float32">
        <value></value>
      </property>
      <property name="accuracy" type="float32">
        <value></value>
      </property>
    </topic>

    <topic name="distance" type="subscribe" description="distance from the object" fileName="Distance">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="range_min" type="float32" unit="metre" description="minimum range value">
        <value></value>
      </property>
      <property name="range_max" type="float32" unit="metre" description="maximum range value">
        <value></value>
      </property>
      <property name="time_measurements" type="float32" unit="second" description="time between measurements">
        <value></value>
      </property>
      <property name="distance" type="float32" unit="metre" description="range data">
        <value></value>
      </property>
    </topic>

    <param name="frame_id" type="string" description="tf frame from which the range_finder is publishing">
      <value></value>
    </param>

    <param name="time_measurements" type="double" unit="second" description="time between measurements">
      <value></value>
    </param>

    <param name="distance_min" type="double" unit="metre" description="the minimum distance to return">
      <value></value>
    </param>

    <param name="distance_max" type="double" unit="metre" description="the maximum distance to return">
      <value></value>
    </param>

  </mandatory>
  <optional>

    <topic name="reconfiguration" type="subscribe" description="dynamic reconfiguration of H-ROS systems" fileName="Reconfiguration">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="orientation" type="quaternion" fileName="Quaternion">
        <xi:include href="../../complex/quaternion.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="orientation_covariance" type="float64[9]">
        <value></value>
      </property>
      <property name="angular_velocity" type="vector3" fileName="Vector3">
        <xi:include href="../../complex/vector3.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="angular_velocity_covariance" type="float64[9]">
        <value></value>
      </property>
      <property name="linear_acceleration" type="vector3" fileName="Vector3">
        <xi:include href="../../complex/vector3.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="linear_acceleration_covariance" type="float64[9]">
        <value></value>
      </property>
    </topic>

  </optional>
</module>

=== AcutronicRobotics/HRIM/models/sensor/lidar/lidar.xml
<?xml version="1.0"?>
<module name="lidar" type="sensor" description="defines the messages to interact with a lidar"
  noNamespaceSchemaLocation="../../schemas/module.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  <mandatory>

    <xi:include href="../../generic/base.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/specs.xml" xpointer="xpointer(//root/topic)"/>

    <xi:include href="topics/scan.xml" xpointer="xpointer(//root/topic)"/>

    <param name="frame_id" type="string" description="tf frame from which the range_finder is publishing">
      <value></value>
    </param>

    <param name="angle_start" type="double" unit="radian" description="start point of scanning angle">
      <value></value>
    </param>

    <param name="angle_end" type="double" unit="radian" description="end point of scanning angle">
      <value></value>
    </param>

    <param name="angle_increment" type="double" unit="radians per radian" description="resolution of laser scan">
      <value></value>
    </param>

    <param name="scan_time" type="double" unit="second" description="time between scans">
      <value></value>
    </param>

    <param name="time_increment" type="double" unit="second" description="time between scans">
      <value></value>
    </param>

    <param name="distance_min" type="double" unit="metre" description="the minimum distance to return">
      <value></value>
    </param>

    <param name="distance_max" type="double" unit="metre" description="the maximum distance to return">
      <value></value>
    </param>

  </mandatory>
  <optional>

    <xi:include href="topics/reconfiguration.xml" xpointer="xpointer(//root/topic)"/>

    <param name="angular_velocity" type="double" unit="radians per second" description="device rotation speed">
      <value></value>
    </param>

    <param name="intensity" type="float" unit="percentage" description="lidar intensity value">
      <value></value>
    </param>

  </optional>
</module>

=== AcutronicRobotics/HRIM/models/sensor/torque/torque.xml
<?xml version="1.0"?>
<module name="torque" type="sensor" description="defines the messages to interact with a torque sensor"
  noNamespaceSchemaLocation="../../schemas/module.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  <mandatory>

    <xi:include href="../../generic/base.xml" xpointer="xpointer(//root/topic)"/>

    <topic name="specs" type="subscribe" description="device features">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="max_torque" type="uint16" unit="newtons per metre" description="maximum measurable torque">
        <value></value>
      </property>
      <property name="resolution" type="float32" unit="newtons per metre" description="maximum measurable torque">
        <value></value>
      </property>
      <property name="device_type" type="uint8" unit="enum" enum='{"STATIC": 0, "ROTARY": 1, "NONCONTACTING": 2}' description="way the sensor detects torque">
        <value></value>
      </property>
      <property name="sensor_direction" type="uint8" unit="enum" enum='{"CLOCKWISE": 0, "COUNTERCLOCKWISE": 1, "BIDIRECTIONAL": 2}' description="rotatory direction the sensor measures">
        <value></value>
      </property>
      <property name="max_rpm" type="uint32" unit="rpm" description="maximum rpm the sensor withstands">
        <value></value>
      </property>
      <property name="safe_overload" type="uint16" unit="percentage" description="maximum force the sensor withstands safely">
        <value></value>
      </property>
      <property name="max_overload" type="uint16" unit="percentage" description="maximum force the sensor withstands before total breakdown">
        <value></value>
      </property>
      <property name="max_rate" type="uint16" unit="hertz" description="maximum amount of measurements per second">
        <value></value>
      </property>
      <property name="min_ideal_temp" type="float32" unit="celsius" description="minimum temperature where the error margin is at it's lowest">
        <value></value>
      </property>
      <property name="max_ideal_temp" type="float32" unit="celsius" description="maximum temperature where the error margin is at it's lowest">
        <value></value>
      </property>
      <property name="min_operating_temp" type="float32" unit="celsius" description="minimum operating temperature">
        <value></value>
      </property>
      <property name="max_operating_temp" type="float32" unit="celsius" description="maximum operating temperature">
        <value></value>
      </property>
      <property name="min_error_margin" type="float32" unit="plus-minus percentage" description="average error margin while inside the ideal temperature ranges">
        <value></value>
      </property>
      <property name="max_error_margin" type="float32" unit="plus-minus percentage" description="average error margin while outside the ideal temperature ranges">
        <value></value>
      </property>
    </topic>

    <topic name="torque" type="subscribe" description="torque force on the measured axis">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="torque" type="float64" unit="newtons per metre" description="torque reading">
        <value></value>
      </property>
    </topic>

    <param name="frame_id" type="string" description="tf frame from which the torque sensor is publishing">
      <value></value>
    </param>

  </mandatory>
</module>
