=== AcutronicRobotics/HRIM/models/schemas/module.xsd
<?xml version="1.0"?>
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  elementFormDefault="qualified">

  <xsd:element name="module">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="mandatory" type="mandatoryType" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="optional" type="optionalType" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="type" type="moduleTypeType" use="required"/>
      <xsd:attribute name="description" type="xsd:string" use="optional"/>
      <xsd:attribute name="noNamespaceSchemaLocation" type="xsd:string" use="required"/>
   </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="mandatoryType">
    <xsd:sequence>
      <xsd:element name="topic" type="topicType" minOccurs="8" maxOccurs="unbounded"/>
      <xsd:element name="param" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="optionalType">
    <xsd:sequence>
      <xsd:element name="topic" type="topicType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="param" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>

  <xsd:complexType name="topicType">
    <xsd:sequence>
      <xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element name="response" type="responseType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="topicTypeType" use="required"/>
    <xsd:attribute name="description" type="xsd:string" use="optional"/>
    <xsd:attribute name="fileName" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="propertyType">
    <xsd:choice>
      <xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element name="value" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:choice>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
    <xsd:attribute name="unit" type="xsd:string" use="optional"/>
    <xsd:attribute name="enum" type="xsd:string" use="optional"/>
    <xsd:attribute name="description" type="xsd:string" use="optional"/>
    <xsd:attribute name="fileName" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="responseType">
    <xsd:choice>
      <xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:choice>
  </xsd:complexType>

  <xsd:simpleType name="moduleTypeType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="actuator"/>
      <xsd:enumeration value="cognition"/>
      <xsd:enumeration value="communication"/>
      <xsd:enumeration value="composite"/>
      <xsd:enumeration value="power"/>
      <xsd:enumeration value="sensor"/>
      <xsd:enumeration value="ui"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="topicTypeType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="publish"/>
      <xsd:enumeration value="subscribe"/>
      <xsd:enumeration value="service"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== AcutronicRobotics/HRIM/models/actuator/gripper/gripper.xml
<?xml version="1.0"?>
<module name="gripper" type="actuator" description="defines the messages to interact with grippers"
  noNamespaceSchemaLocation="../../schemas/module.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  <mandatory>

    <xi:include href="../../generic/base.xml" xpointer="xpointer(//root/topic)"/>

    <topic name="specs" type="subscribe" description="main characteristics of the finger gripper" fileName="SpecsFingerGripper">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="min_force" type="float32" unit="newton" description="minimum gripping force">
        <value></value>
      </property>
      <property name="max_force" type="float32" unit="newton" description="maximum gripping force">
        <value></value>
      </property>
      <property name="max_payload" type="float32" unit="kilogram" description="maximum recommended payload">
        <value></value>
      </property>
      <property name="min_speed" type="float32" unit="millimeters per second" description="minimum closing speed, if equal to max_speed the component doesn't have that capability">
        <value></value>
      </property>
      <property name="max_speed" type="float32" unit="millimeters per second" description="maximum closing speed, if equal to min_speed the component doesn't have that capability">
        <value></value>
      </property>
      <property name="max_acceleration" type="float32" unit="millimeters per second squared" description="maximum acceleration, if 0 the component doesn't have that capability">
        <value></value>
      </property>
      <property name="max_length" type="float32" unit="millimeter" description="maximum permitted finger length">
        <value></value>
      </property>
      <property name="max_angle" type="float32" unit="radian" description="maximum permitted finger angle">
        <value></value>
      </property>
      <property name="repeatability" type="float32" unit="second" description="parallel grip repeatability">
        <value></value>
      </property>
    </topic>

    <topic name="specs" type="subscribe" description="main characteristics of the magnetic gripper" fileName="SpecsMagneticGripper">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="magnetic_force" type="float32" unit="newton" description="the magnet's force">
        <value></value>
      </property>
      <property name="max_payload" type="float32" unit="kilogram" description="maximum payload">
        <value></value>
      </property>
    </topic>

    <topic name="specs" type="subscribe" description="main characteristics of the vacuum gripper" fileName="SpecsVacuumGripper">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="cycle_time" type="float32" unit="second" description="needed time for one cycle">
        <value></value>
      </property>
      <property name="max_force" type="float32" unit="newton" description="taking into account 100% vacuum and with non-porous material">
        <value></value>
      </property>
      <property name="max_payload" type="float32" unit="kilogram" description="maximum recommended payload">
        <value></value>
      </property>
    </topic>

    <topic name="goal" type="service" description="orders the gripper to grab or release" fileName="GoalGripper">
      <property name="on_off" type="boolean" description="true: grab the object | false: release the object">
        <value></value>
      </property>
      <response>
        <property name="goal_accepted" type="boolean" description="true: the goal is accepted | false: the goal is not accepted">
          <value></value>
        </property>
      </response>
    </topic>

    <topic name="state" type="subscribe" description="notify if the gripper is activate or not" fileName="StateGripper">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="on_off" type="boolean" description="true: the gripper is active | false: the gripper is inactive">
        <value></value>
      </property>
    </topic>

  </mandatory>
  <optional>

    <topic name="goalpro" type="service" description="allows the user to work with different values" fileName="ControlFinger">
      <property name="goal_linearposition" type="float32" unit="metre" description="distance between fingers">
        <value></value>
      </property>
      <property name="goal_angularposition" type="float32" unit="radian" description="angle of the joint">
        <value></value>
      </property>
      <property name="goal_effort" type="float32" unit="newton" description="maximun effort to apply">
        <value></value>
      </property>
      <property name="goal_velocity" type="float32" unit="metres per second" description="velocity to open/close fingers, if 0 gripper contains pressure sensor">
        <value></value>
      </property>
      <property name="goal_acceleration" type="float32" unit="metres per second squared" description="acceleration to open fingers">
        <value></value>
      </property>
      <response>
        <property name="goal_accepted" type="boolean" description="true: the goal is accepted | false: the goal is not accepted">
          <value></value>
        </property>
      </response>
    </topic>

    <topic name="goalpro" type="service" description="allows the user to work with different suction values" fileName="ControlVacuum">
      <property name="goal_percentage_suction" type="float32" unit="percentage" description="suction value on the maximum allowed">
        <value></value>
      </property>
      <response>
        <property name="goal_accepted" type="boolean" description="true: the goal is accepted | false: the goal is not accepted">
          <value></value>
        </property>
      </response>
    </topic>

    <topic name="state_finder_gripper" type="subscribe" description="finger gripper state is at this time" fileName="StateFingerGripper">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="angular_position" type="float32">
        <value></value>
      </property>
      <property name="linear_position" type="float32">
        <value></value>
      </property>
    </topic>

    <topic name="cycle_time" type="subscribe" description="time that the gripper must take to complete the cycle: the time between catching the object and leaving it" fileName="CycleTime">
      <property name="header" type="header" origin="generic/header.xml" description="the acquisition time of the completed cycle">
        <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property/property)"/>
      </property>
      <property name="cycle_time" type="float32" unit="second" description="pick and place cycle time">
        <value></value>
      </property>
    </topic>

    <topic name="goal_pressure" type="subscribe" description="maximum pressure that the gripper will make on the object" fileName="GoalTactilePressure">
      <property name="header" type="header" origin="generic/header.xml" description="pressure is at this time">
        <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property/property)"/>
      </property>
      <property name="goal_pressure" type="float32" unit="newtons per meters squared" description="maximum pressure fingers can make">
        <value></value>
      </property>
    </topic>

    <topic name="reconfiguration" type="subscribe" description="dynamic reconfiguration of H-ROS systems" fileName="Reconfiguration">
      <xi:include href="../../generic/header.xml" xpointer="xpointer(//root/property)"/>
      <property name="orientation" type="quaternion" origin="complex/quaternion.xml">
        <xi:include href="../../complex/quaternion.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="orientation_covariance" type="float64[9]">
        <value></value>
      </property>
      <property name="angular_velocity" type="vector3" origin="complex/vector3.xml">
        <xi:include href="../../complex/vector3.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="angular_velocity_covariance" type="float64[9]">
        <value></value>
      </property>
      <property name="linear_acceleration" type="vector3" origin="complex/vector3.xml">
        <xi:include href="../../complex/vector3.xml" xpointer="xpointer(//root/property)"/>
      </property>
      <property name="linear_acceleration_covariance" type="float64[9]">
        <value></value>
      </property>
    </topic>

  </optional>
</module>
